apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: monitor-route
  namespace: monitoring
spec:
  parentRefs:
    - name: polom-gateway
      namespace: default
  hostnames:
    - monitor.shanana.shop
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-stack-grafana
          port: 80

---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: monitor-route
  namespace: monitoring
spec:
  parentRefs:
    - kind: Gateway
      name: polom-gateway
      namespace: default
      sectionName: https
  hostnames:
    - "monitor.shanana.shop"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: prometheus-stack-grafana
          port: 80
